export const START_ACTION = 'START_ACTION';
export const FINISH_ACTION = 'FINISH_ACTION';

export const CLEAR_DRAFT = 'CLEAR_DRAFT';

export const CLEAR_PAGINATION_SEARCHPARAMS = 'CLEAR_PAGINATION_SEARCHPARAMS';
