export const LOAD_TOWN_DATA_START = 'LOAD_TOWN_DATA_START';
export const LOAD_TOWN_DATA_SUCCESS = 'LOAD_TOWN_DATA_SUCCESS';
export const LOAD_TOWN_DATA_FAIL = 'LOAD_TOWN_DATA_FAIL';

export const LOAD_STATIONS_PANEL_START = 'LOAD_STATIONS_PANEL_START';
export const LOAD_STATIONS_PANEL_SUCCESS = 'LOAD_STATIONS_PANEL_SUCCESS';
export const LOAD_STATIONS_PANEL_FAIL = 'LOAD_STATIONS_PANEL_FAIL';

export const ADD_STATION_START = 'ADD_STATION_START';
export const ADD_STATION_SUCCESS = 'ADD_STATION_SUCCESS';
export const ADD_STATION_FAIL = 'ADD_STATION_FAIL';

export const ADD_CONNECTION_START = 'ADD_CONNECTION_START';
export const ADD_CONNECTION_SUCCESS = 'ADD_CONNECTION_SUCCESS';
export const ADD_CONNECTION_FAIL = 'ADD_CONNECTION_FAIL';

export const DELETE_CONNECTION_START = 'DELETE_CONNECTION_START';
export const DELETE_CONNECTION_SUCCESS = 'DELETE_CONNECTION_SUCCESS';
export const DELETE_CONNECTION_FAIL = 'DELETE_CONNECTION_FAIL';

export const UPDATE_STATION_START = 'UPDATE_STATION_START';
export const UPDATE_STATION_SUCCESS = 'UPDATE_STATION_SUCCESS';
export const UPDATE_STATION_FAIL = 'UPDATE_STATION_FAIL';

export const SEARCH_CONNECTIONS_START = 'SEARCH_CONNECTIONS_START';
export const SEARCH_CONNECTIONS_SUCCESS = 'SEARCH_CONNECTIONS_SUCCESS';
export const SEARCH_CONNECTIONS_FAIL = 'SEARCH_CONNECTIONS_FAIL';

export const SEARCH_LINES_START = 'SEARCH_LINES_START';
export const SEARCH_LINES_SUCCESS = 'SEARCH_LINES_SUCCESS';
export const SEARCH_LINES_FAIL = 'SEARCH_LINES_FAIL';

export const SEARCH_STATIONS_START = 'SEARCH_STATIONS_START';
export const SEARCH_STATIONS_SUCCESS = 'SEARCH_STATIONS_SUCCESS';
export const SEARCH_STATIONS_FAIL = 'SEARCH_STATIONS_FAIL';
