export const ADD_CONNECTION_START = 'ADD_CONNECTION_START';
export const ADD_CONNECTION_SUCCESS = 'ADD_CONNECTION_SUCCESS';
export const ADD_CONNECTION_FAIL = 'ADD_CONNECTION_FAIL';

export const EDIT_STATION_START = 'EDIT_STATION_START';
export const EDIT_STATION_SUCCESS = 'EDIT_STATION_SUCCESS';
export const EDIT_STATION_FAIL = 'EDIT_STATION_FAIL';

export const SEARCH_CONNECTIONS_START = 'SEARCH_CONNECTIONS_START';
export const SEARCH_CONNECTIONS_SUCCESS = 'SEARCH_CONNECTIONS_SUCCESS';
export const SEARCH_CONNECTIONS_FAIL = 'SEARCH_CONNECTIONS_FAIL';

export const SEARCH_LINES_START = 'SEARCH_LINES_START';
export const SEARCH_LINES_SUCCESS = 'SEARCH_LINES_SUCCESS';
export const SEARCH_LINES_FAIL = 'SEARCH_LINES_FAIL';

export const SEARCH_STATIONS_START = 'SEARCH_STATIONS_START';
export const SEARCH_STATIONS_SUCCESS = 'SEARCH_STATIONS_SUCCESS';
export const SEARCH_STATIONS_FAIL = 'SEARCH_STATIONS_FAIL';
