export const SEARCH_PARAMS_CHANGE_START = 'SEARCH_PARAMS_CHANGE_START';
export const SEARCH_PARAMS_CHANGE_SUCCESS = 'SEARCH_PARAMS_CHANGE_SUCCESS';
export const SEARCH_PARAMS_CHANGE_FAIL = 'SEARCH_PARAMS_CHANGE_FAIL';
