export const YEAR_CHANGED = 'YEAR_CHANGED';
export const SET_YEAR = 'SET_YEAR';
export const TOGGLE_YEAR_SELECTOR = 'TOGGLE_YEAR_SELECTOR';
export const LOAD_STATIONS_START = 'LOAD_STATIONS_START';
export const LOAD_STATIONS_SUCCESS = 'LOAD_STATIONS_SUCCESS';
export const LOAD_STATIONS_FAIL = 'LOAD_STATIONS_FAIL';

// Admin

export const ADMIN_SEARCH_STATIONS_START = 'ADMIN_SEARCH_STATIONS_START';
export const ADMIN_SEARCH_STATIONS_SUCCESS = 'ADMIN_SEARCH_STATIONS_SUCCESS';
export const ADMIN_SEARCH_STATIONS_FAIL = 'ADMIN_SEARCH_STATIONS_FAIL';

export const ADMIN_SEARCH_CONNECTIONS_START = 'ADMIN_SEARCH_CONNECTIONS_START';
export const ADMIN_SEARCH_CONNECTIONS_SUCCESS = 'ADMIN_SEARCH_CONNECTIONS_SUCCESS';
export const ADMIN_SEARCH_CONNECTIONS_FAIL = 'ADMIN_SEARCH_CONNECTIONS_FAIL';

export const ADMIN_EDIT_STATION_START = 'ADMIN_EDIT_STATION_START';
export const ADMIN_EDIT_STATION_SUCCESS = 'ADMIN_EDIT_STATION_SUCCESS';
export const ADMIN_EDIT_STATION_FAIL = 'ADMIN_EDIT_STATION_FAIL';

export const ADMIN_ADD_CONNECTION_START = 'ADMIN_ADD_CONNECTION_START';
export const ADMIN_ADD_CONNECTION_SUCCESS = 'ADMIN_ADD_CONNECTION_SUCCESS';
export const ADMIN_ADD_CONNECTION_FAIL = 'ADMIN_ADD_CONNECTION_FAIL';
