export const ADD_CONNECTION_START = 'ADD_CONNECTION_START';
export const ADD_CONNECTION_SUCCESS = 'ADD_CONNECTION_SUCCESS';
export const ADD_CONNECTION_FAIL = 'ADD_CONNECTION_FAIL';

export const UPDATE_CONNECTION_START = 'UPDATE_CONNECTION_START';
export const UPDATE_CONNECTION_SUCCESS = 'UPDATE_CONNECTION_SUCCESS';
export const UPDATE_CONNECTION_FAIL = 'UPDATE_CONNECTION_FAIL';

export const DELETE_CONNECTION_START = 'DELETE_CONNECTION_START';
export const DELETE_CONNECTION_SUCCESS = 'DELETE_CONNECTION_SUCCESS';
export const DELETE_CONNECTION_FAIL = 'DELETE_CONNECTION_FAIL';
