export const LOAD_STATIONS_PANEL_START = 'LOAD_STATIONS_PANEL_START';
export const LOAD_STATIONS_PANEL_SUCCESS = 'LOAD_STATIONS_PANEL_SUCCESS';
export const LOAD_STATIONS_PANEL_FAIL = 'LOAD_STATIONS_PANEL_FAIL';

export const ADD_STATION_START = 'ADD_STATION_START';
export const ADD_STATION_SUCCESS = 'ADD_STATION_SUCCESS';
export const ADD_STATION_FAIL = 'ADD_STATION_FAIL';

export const ADD_CONNECTION_START = 'ADD_CONNECTION_START';
export const ADD_CONNECTION_SUCCESS = 'ADD_CONNECTION_SUCCESS';
export const ADD_CONNECTION_FAIL = 'ADD_CONNECTION_FAIL';

export const DELETE_CONNECTION_START = 'DELETE_CONNECTION_START';
export const DELETE_CONNECTION_SUCCESS = 'DELETE_CONNECTION_SUCCESS';
export const DELETE_CONNECTION_FAIL = 'DELETE_CONNECTION_FAIL';

export const UPDATE_STATION_START = 'UPDATE_STATION_START';
export const UPDATE_STATION_SUCCESS = 'UPDATE_STATION_SUCCESS';
export const UPDATE_STATION_FAIL = 'UPDATE_STATION_FAIL';

export const SEARCH_CONNECTIONS_START = 'SEARCH_CONNECTIONS_START';
export const SEARCH_CONNECTIONS_SUCCESS = 'SEARCH_CONNECTIONS_SUCCESS';
export const SEARCH_CONNECTIONS_FAIL = 'SEARCH_CONNECTIONS_FAIL';

export const SEARCH_LINES_START = 'SEARCH_LINES_START';
export const SEARCH_LINES_SUCCESS = 'SEARCH_LINES_SUCCESS';
export const SEARCH_LINES_FAIL = 'SEARCH_LINES_FAIL';

export const SEARCH_STATIONS_START = 'SEARCH_STATIONS_START';
export const SEARCH_STATIONS_SUCCESS = 'SEARCH_STATIONS_SUCCESS';
export const SEARCH_STATIONS_FAIL = 'SEARCH_STATIONS_FAIL';

export const UPLOAD_TOWN_DATA_START = 'UPLOAD_TOWN_DATA_START';
export const UPLOAD_TOWN_DATA_SUCCESS = 'UPLOAD_TOWN_DATA_SUCCESS';
export const UPLOAD_TOWN_DATA_FAIL = 'UPLOAD_TOWN_DATA_FAIL';

export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const GET_TOWNS_START = 'GET_TOWNS_START';
export const GET_TOWNS_SUCCESS = 'GET_TOWNS_SUCCESS';
export const GET_TOWNS_FAIL = 'GET_TOWNS_FAIL';

export const GET_TOWN_START = 'GET_TOWN_START';
export const GET_TOWN_SUCCESS = 'GET_TOWN_SUCCESS';
export const GET_TOWN_FAIL = 'GET_TOWN_FAIL';

export const GET_LINES_START = 'GET_LINES_START';
export const GET_LINES_SUCCESS = 'GET_LINES_SUCCESS';
export const GET_LINES_FAIL = 'GET_LINES_FAIL';
