export const ADD_STATION_START = 'ADD_STATION_START';
export const ADD_STATION_SUCCESS = 'ADD_STATION_SUCCESS';
export const ADD_STATION_FAIL = 'ADD_STATION_FAIL';

export const UPDATE_STATION_START = 'UPDATE_STATION_START';
export const UPDATE_STATION_SUCCESS = 'UPDATE_STATION_SUCCESS';
export const UPDATE_STATION_FAIL = 'UPDATE_STATION_FAIL';

export const DELETE_STATION_START = 'DELETE_STATION_START';
export const DELETE_STATION_SUCCESS = 'DELETE_STATION_SUCCESS';
export const DELETE_STATION_FAIL = 'DELETE_STATION_FAIL';