export const GET_DRAFT_START = 'GET_DRAFT_START';
export const GET_DRAFT_SUCCESS = 'GET_DRAFT_SUCCESS';
export const GET_DRAFT_FAIL = 'GET_DRAFT_FAIL';

export const ADD_DRAFT_START = 'ADD_DRAFT_START';
export const ADD_DRAFT_SUCCESS = 'ADD_DRAFT_SUCCESS';
export const ADD_DRAFT_FAIL = 'ADD_DRAFT_FAIL';

export const UPDATE_DRAFT_START = 'UPDATE_DRAFT_START';
export const UPDATE_DRAFT_SUCCESS = 'UPDATE_DRAFT_SUCCESS';
export const UPDATE_DRAFT_FAIL = 'UPDATE_DRAFT_FAIL';

export const DELETE_DRAFT_START = 'DELETE_DRAFT_START';
export const DELETE_DRAFT_SUCCESS = 'DELETE_DRAFT_SUCCESS';
export const DELETE_DRAFT_FAIL = 'DELETE_DRAFT_FAIL';
