export const LOAD_INIT_START = 'LOAD_INIT_START';
export const LOAD_INIT_SUCCESS = 'LOAD_INIT_SUCCESS';
export const LOAD_INIT_FAIL = 'LOAD_INIT_FAIL';

export const LOAD_LINE_DETAILS_START = 'LOAD_LINE_DETAILS_START';
export const LOAD_LINE_DETAILS_SUCCESS = 'LOAD_LINE_DETAILS_SUCCESS';
export const LOAD_LINE_DETAILS_FAIL = 'LOAD_LINE_DETAILS_FAIL';

export const CHANGE_YEAR_START = 'CHANGE_YEAR_START';
export const CHANGE_YEAR_SUCCESS = 'CHANGE_YEAR_SUCCESS';
export const CHANGE_YEAR_FAIL = 'CHANGE_YEAR_FAIL';

export const GET_STATION_DETAILS_START = 'GET_STATION_DETAILS_START';
export const GET_STATION_DETAILS_SUCCESS = 'GET_STATION_DETAILS_SUCCESS';
export const GET_STATION_DETAILS_FAIL = 'GET_STATION_DETAILS_FAIL';

export const SET_MAP_STATE = 'SET_MAP_STATE';

export const SET_SIDE_BAR_MODE = 'SET_SIDE_BAR_MODE';
