export const ADD_LINE_START = 'ADD_LINE_START';
export const ADD_LINE_SUCCESS = 'ADD_LINE_SUCCESS';
export const ADD_LINE_FAIL = 'ADD_LINE_FAIL';

export const UPDATE_LINE_START = 'UPDATE_LINE_START';
export const UPDATE_LINE_SUCCESS = 'UPDATE_LINE_SUCCESS';
export const UPDATE_LINE_FAIL = 'UPDATE_LINE_FAIL';

export const DELETE_LINE_START = 'DELETE_LINE_START';
export const DELETE_LINE_SUCCESS = 'DELETE_LINE_SUCCESS';
export const DELETE_LINE_FAIL = 'DELETE_LINE_FAIL';
